# Generated by Django 4.2.5 on 2023-10-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_Log_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
