# Generated by Django 4.2.5 on 2023-10-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_Log_App', '0002_alter_member_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
